config/routes.rb
match 'favorite_projects/index',
      to: 'favorite_projects#index',
      via: [:get]
match 'favorite_projects/favorite',
      to: 'favorite_projects#favorite',
      via: [:get]
match 'favorite_projects/unfavorite',
      to: 'favorite_projects#unfavorite',
      via: [:get, :delete]
match 'favorite_projects/search',
      to: 'favorite_projects#search',
      via: [:get, :put, :post],
      as: 'search_favorite_projects'

app/models/favorite_project.rb
# encoding: utf-8
#

class FavoriteProject < ActiveRecord::Base
  def self.favorite?(project_id, user_id = User.current.id)
    FavoriteProject.find_by_project_id_and_user_id(project_id, user_id).nil?
  end
end

app/controllers/favorite_projects_controller.rb
# encoding: utf-8
#

class FavoriteProjectsController < ApplicationController
  before_action :find_project_by_project_id, except: :search
  helper ProjectsHelper

  def search
    seach = params[:q] || params[:project_search]

    scope = Project.visible
    scope = Project.active unless params[:closed]
    scope = scope.where(["(LOWER(#{Project.table_name}.name) LIKE ? OR
                         LOWER(#{Project.table_name}.description) LIKE ?)",
                         '%' + seach.downcase + '%',
                         '%' + seach.downcase + '%']) unless seach.blank?

    @projects = scope.visible.order('lft').all

    respond_to do |format|
      format.html { render template: 'projects/index' }
      format.js { render partial: 'search' }
    end
  end

  def favorite
    if @project.respond_to?(:visible?) && !@project.visible?(User.current)
      render_403
    else
      set_favorite(User.current, true)
    end
  end

  def unfavorite
    set_favorite(User.current, false)
  end

  private

  def set_favorite(user, favorite)
    if favorite
      favorite_project = FavoriteProject.find_by_project_id_and_user_id(@project.id, user.id)
      favorite_project.delete if favorite_project
    else
      FavoriteProject.create(project_id: @project.id, user_id: user.id)
    end
    Rails.cache.clear

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render partial: 'set_favorite' }
    end

  rescue ::ActionController::RedirectBackError
    render text: (favorite ? 'Favorite added.' : 'Favorite removed.'), layout: true
  end
end

app/helpers/favorite_projects_helper.rb
# encoding: utf-8
#

module FavoriteProjectsHelper
  # include ProjectsHelper
  def favorite_tag(object, user)
    favorite = FavoriteProject.favorite?(object.id, user.id)
    default_favorite_behavior = Setting.plugin_redmine_favorite_projects['default_favorite_behavior'].to_s.empty?
    favorite_batch_tag(object, user, favorite, default_favorite_behavior)
  end

  def favorite_batch_tag(object, user, favorite, default_favorite_behavior)
    return '' unless user && user.logged? && user.member_of?(object)
    if default_favorite_behavior
      image_a = 'fav_off.png'
      image_b = 'fav.png'
    else
      image_a = 'fav.png'
      image_b = 'fav_off.png'
    end

    url = { controller: 'favorite_projects',
            action: (favorite ? 'unfavorite' : 'favorite'),
            project_id: object.id }
    link = link_to(image_tag(favorite ? image_a : image_b, style: 'vertical-align: middle;'),
                   url,
                   remote: true)
    content_tag('span', link, id: "favorite_project_#{object.id}").html_safe
  end

  # Returns the css class used to identify watch links for a given +object+
  def favorite_css(objects)
    objects = Array.wrap(objects)
    "#{objects.first.class.to_s.underscore}-#{object.id}-favorite"
  end

  def table_view_modules_links(project)
    links = []
    menu_items_for(:project_menu, project) do |node|
      unless node.name == :overview || node.name == :new_object
        links << link_to(extract_node_details(node, project)[0],
                         extract_node_details(node, project)[1])
      end
    end
    links.join(', ').html_safe
  end

  def project_index_cache_key
    cache_key = ['projects/index',
                 "user-#{User.current.id}/#{User.current.updated_on.iso8601}",
                 Project.visible.order('updated_on desc').first,
                 MemberRole.last]

    unless Setting.plugin_redmine_favorite_projects['show_project_modules'].blank?
      cache_key << EnabledModule.last
    end

    unless Setting.plugin_redmine_favorite_projects['show_project_progress'].blank?
      progress_key = Issue.visible.order('issues.updated_on desc').first
      unless progress_key.nil?
        cache_key << "issue-#{progress_key.updated_on.iso8601}"
      end
    end
    cache_key
  end

  def project_manager_list(project)
    managers = ''
    manager_name = Setting.plugin_redmine_favorite_projects['project_manager_name'].to_s
    unless manager_name.empty?
      @users_by_role = project.users_by_role
      @users_by_role.keys.sort.each do |role|
        if role.to_s == manager_name
          managers = @users_by_role[role].sort.collect { |u| link_to_user u }.join(', ').html_safe
          break
        end
      end
    end
    managers
  end

  def table_view_progress(project)
    s = ''
    return s unless User.current.allowed_to?(:view_issues, project)

    cond = project.project_condition(false)
    open_issues = Issue.visible.open.where(cond).count
    all_issues = Issue.visible.where(cond).count

    if open_issues > 0
      issues_closed_percent = (1 - open_issues.to_f / all_issues) * 100
      s << '<div>Issues: ' +
           link_to("#{open_issues} open", controller: 'issues', action: 'index', project_id: project, set_filter: 1) +
           "<small> / #{all_issues} total</small></div>" +
           progress_bar(issues_closed_percent,
                        width: '30em',
                        legend: format('%0.0f%', issues_closed_percent))
    end
    project_versions = project_open(project)

    unless project_versions.empty?
      s << '<div>'
      project_versions.reverse_each do |version|
        next if version.completed?
        s << "<div style=\"clear:both; display: block\">#{link_to_version(version)}: " +
             link_to_if(version.open_issues_count > 0,
                        l(:label_x_open_issues_abbr, count: version.open_issues_count),
                        controller: 'issues',
                        action: 'index',
                        project_id: version.project, status_id: 'o', fixed_version_id: version, set_filter: 1) +
             '<small> / ' +
             link_to_if(version.closed_issues_count > 0,
                        l(:label_x_closed_issues_abbr, count: version.closed_issues_count),
                        controller: 'issues',
                        action: 'index',
                        project_id: version.project, status_id: 'c', fixed_version_id: version, set_filter: 1) + '</small>. '
        s << due_date_distance_in_words(version.effective_date) if version.effective_date
        s << '</div><br />' +
             progress_bar([version.closed_percent, version.completed_percent],
                          width: '30em',
                          legend: format('%0.0f%', version.completed_percent))
      end
      s << '</div>'
    end
    s.html_safe
  end

  def project_open(project)
    with_subprojects = Setting.display_subprojects_issues?
    project_ids = with_subprojects ? project.self_and_descendants.collect(&:id) : [project.id]

    versions = project.shared_versions || []
    versions += project.rolled_up_versions.visible if with_subprojects
    versions = versions.uniq.sort
    completed_versions = versions.select { |version| version.closed? || version.completed? }
    versions -= completed_versions

    issues_by_version = {}
    versions.reject! { |version| !project_ids.include?(version.project_id) && issues_by_version[version].blank? }
    versions
  end
end

app/views/favorite_projects/_search.html.erb
  $('#projects_list').html("<%= escape_javascript render :partial => 'projects/list' %>")

app/views/favorite_projects/_set_favorite.js.erb
<% selector = "#favorite_project_#{@project.id}" %>
$("<%= selector %>").each(function(){$(this).replaceWith("<%= escape_javascript favorite_tag(@project, User.current) %>")});
<% @project = nil %>
$('#quick-search > select').html("<%= escape_javascript render_project_jump_box %>")

app/views/favorite_projects/_update_menu.html.erb
<% if (Setting.plugin_redmine_favorite_projects['show_in_app_menu']) && @project.nil? %>
<div style="display:none">
<div id="fav_projs">
    <% favorite_projects = favorite_list %>
    <% if !favorite_projects.nil? && favorite_projects.any? %>
        <% favorite_projects.each do |fav| %>
            <li><%= project_name(fav.project, false, class: 'icon') %></li>
        <% end %>
    <% end %>
</div>
</div>
  <script>
  (function() {
    var fav_projs_ = document.getElementById("fav_projs"),
      fav_menu_ = document.getElementById("favorite-menu");
    // Inject projects before menu, and dispose old menu container after
    fav_menu_.parentNode.insertBefore(fav_projs_, fav_menu_);
    fav_menu_.parentNode.removeChild(fav_menu_);
    })();
  </script>
<% end %>

app/views/projects/_list.html.erb
<%

   show_project_desc = Setting.plugin_redmine_favorite_projects['show_project_desc'].to_s
   show_project_manager = Setting.plugin_redmine_favorite_projects['show_project_manager']
   show_project_created_on = Setting.plugin_redmine_favorite_projects['show_project_created_on'].to_s
   show_project_homepage = Setting.plugin_redmine_favorite_projects['show_project_homepage'].to_s
   show_project_modules = Setting.plugin_redmine_favorite_projects['show_project_modules'].to_s
   show_project_progress = Setting.plugin_redmine_favorite_projects['show_project_progress'].to_s
   default_favorite_behavior = Setting.plugin_redmine_favorite_projects['default_favorite_behavior'].to_s.empty?
   unless show_project_manager.nil? || show_project_manager==0
     manager_name = Setting.plugin_redmine_favorite_projects['project_manager_name'].to_s
   else
     manager_name = ''
   end
   favorite_projects = FavoriteProject.where(user_id: User.current).pluck(:project_id)
   parent_projects = Project.visible.distinct.pluck(:parent_id)
%>
<% if @projects.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>

    <p class="other-formats">
      <%= link_to(l(:expand_all), "#", :onclick => 'expandAll()')%><span>&nbsp;/&nbsp;</span><%= link_to l(:collapse_all), "#", :onclick => 'collapseAll()' %>
    </p>

    <table class="list">
      <thead><tr>
        <th></th>
        <th><%=l(:label_project)%></th>
        <% unless show_project_desc.empty? %><th><%=l(:field_description)%></th><% end %>
        <% unless manager_name.empty? %><th><%= manager_name.html_safe %></th><% end %>
        <% unless show_project_modules.empty? %><th><%= l(:field_go_to)%></th><% end %>
        <% unless show_project_progress.empty? %><th><%= l(:field_versions)%></th><% end %>
        <% unless show_project_homepage.empty? %><th><%=l(:field_homepage)%></th><% end %>
        <% unless show_project_created_on.empty? %><th><%= l(:field_created_on)%></th><% end %>
      </tr></thead>
      <tbody>
      <% ancestors = [] %>
      <% plevel = 0 %>
      <% project_tree(@projects) do |project, level| %>
          <% project_id = "%04d" % project.id %>
          <% (plevel - level).times { ancestors.pop } if (level < plevel) %>
          <% has_children = parent_projects.include?(project.id) %>
          <tr id="<%= project_id %>" class="<%= favorite_css_classes(project, has_children) %> <%= level > 0 ? "hide #{ancestors.last}" : cycle("odd", "even") %>">
            <td class="favorite">
              <%= favorite_batch_tag(project, User.current, !favorite_projects.include?(project.id), default_favorite_behavior) %>
            </td>
            <td class="name" style="padding-left: <%= (18 * level).to_s %>px">
              <% if has_children %>
                  <span class="expander" onclick="toggleShowHide(<%= "'#{project_id}'" %>)">&nbsp;</span>
              <% end %>
              <%= project_name(project) %>
            </td>

            <% unless show_project_desc.empty? %><td class="field"><%= textilizable(project.short_description).html_safe %></td><% end %>
            <% unless manager_name.empty?%><td class="field"><%= project_manager_list(project) %></td><% end %>
            <% unless show_project_modules.empty? %><td class="field"><%= table_view_modules_links(project) %></td><% end %>
            <% unless show_project_progress.empty? %><td class="field"><%= table_view_progress(project) %></td><% end %>
            <% unless show_project_homepage.empty? %><td class="field"><% unless project.homepage.blank? %>
                <%= link_to h(project.homepage), project.homepage, {:class => 'external'} %>
            <% end %></td><% end %>
            <% unless show_project_created_on.empty? %><td><%= format_date(project.created_on) %></td><% end %>
          </tr>
          <% ancestors << project_id if has_children %>
          <% plevel = level %>
      <% end %>
      </tbody>
    </table>

    <p class="other-formats">
      <%= link_to(l(:expand_all), "#", :onclick => 'expandAll()')%><span>&nbsp;/&nbsp;</span><%= link_to l(:collapse_all), "#", :onclick => 'collapseAll()' %>
    </p>

<% end %>

app/views/projects/index.html.erb
<% content_for :header_tags do %>
    <%= javascript_include_tag 'table_view', :plugin => 'redmine_favorite_projects' %>
    <%= stylesheet_link_tag 'table_view', :plugin => 'redmine_favorite_projects' %>
    <%= auto_discovery_link_tag(:atom, {:action => 'index', :format => 'atom', :key => User.current.rss_key}) %>
<% end %>

<div class="contextual">
  <%= render_project_action_links %>
</div>

<%= form_tag({:controller => "favorite_projects", :action => "search"}, :method => :get,  :id => "query_form") do %>
  <% no_filters = (params[:closed].blank? && params[:project_search].blank?) %>

<h2>
  <%=l(:label_project_plural)%>

        <span class="live_search">
            <%= text_field_tag(:project_search, params[:project_search], :autocomplete => "off", :class => "live_search_field", :placeholder => l(:label_search) ) %>
            <%= javascript_tag "observeSearchfield('project_search', 'null', '#{ escape_javascript(search_favorite_projects_path(:format => "js")) }')" %>
        </span>
</h2>

<div class="filters">
    <fieldset id="filters" class="collapsible <%= 'collapsed' if no_filters %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= 'display: none;' if no_filters %>">
        <p>
          <span class="filter-condition">
            <label for="closed"><%= check_box_tag 'closed', 1, params[:closed] %> <%= l(:label_show_closed_projects) %></label>
          </span>

        </p>

      </div>
    </fieldset>
    <p class="buttons hide-when-print">
        <%= link_to l(:button_apply), "#", :onclick=>"$('#query_form').submit()", :class => 'icon icon-checked' %>
        <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
    </p>
</div>

<% end %>
<% cache project_index_cache_key do %>
<div class="autoscroll" id="projects_list">
  <%= render :partial => 'projects/list' %>
</div>
<% end %>

<% if User.current.logged? %>
<p class="other-formats">
<span class="my-project"><%= l(:label_favorite_projects) %></span>
</p>
<% end %>

<% other_formats_links do |f| %>
	<%= f.link_to 'Atom', :url => {:key => User.current.rss_key} %>
<% end %>

<% html_title(l(:label_project_plural)) -%>

app/views/settings/_favorite_projects.html.erb
<p>
  <%= content_tag(:label, l(:label_default_favorite_behavior)) %>
  <%= check_box_tag 'settings[default_favorite_behavior]', 1, @settings['default_favorite_behavior'] %>
  <em class="info"><%= t(:default_favorite_behavior_info_html) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_show_in_app_menu)) %>
  <%= check_box_tag 'settings[show_in_app_menu]', 1, @settings['show_in_app_menu'] %>
  <em class="info"><%= t(:show_in_app_menu_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_project_name_view)) %>
  <%= select_tag 'settings[project_name_view]', project_name_for_select(@settings['project_name_view'].to_s) %>
  <em class="info"><%= t(:project_name_view_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_show_project_desc)) %>
  <%= check_box_tag 'settings[show_project_desc]', 1, @settings['show_project_desc'] %>
  <em class="info"><%= l(:show_project_desc_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_show_project_manager)) %>
  <%= check_box_tag 'settings[show_project_manager]', 1, @settings['show_project_manager'] %>
  <em class="info"><%= l(:show_project_manager_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_project_manager_name)) %>
  <%= select_tag 'settings[project_manager_name]', roles_for_select(@settings['project_manager_name'].to_s) %>
  <em class="info"><%= t(:project_manager_name_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_show_project_modules)) %>
  <%= check_box_tag 'settings[show_project_modules]', 1, @settings['show_project_modules'] %>
  <em class="info"><%= l(:show_project_modules_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_show_project_progress)) %>
  <%= check_box_tag 'settings[show_project_progress]', 1, @settings['show_project_progress'] %>
  <em class="info"><%= l(:show_project_progress_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_show_project_homepage)) %>
  <%= check_box_tag 'settings[show_project_homepage]', 1, @settings['show_project_homepage'] %>
  <em class="info"><%= l(:show_project_homepage_info) %></em>
</p>

<p>
  <%= content_tag(:label, l(:label_show_project_created_on)) %>
  <%= check_box_tag 'settings[show_project_created_on]', 1, @settings['show_project_created_on'] %>
  <em class="info"><%= l(:show_project_created_on_info) %></em>
</p>